### PR TITLE
Declare language of code samples in README

### PR DESCRIPTION
**Pull request by jeremy-audet**
Markdown code fences can be annotated with the language of the code
contained therein. This annotation is recognized by at least the
CommonMark standard and GitHub's implementation of markdown.

### CODE REVIEW

**Comment by jeremy-audet** [comment]
I'm unsure of whether Ansible galaxy supports annotated code fences.

**Comment by jtyr** [comment]
Please could you verify if Galaxy portal will display it correctly?

**Comment by jeremy-audet** [comment]
From the [Ansible Galaxy README.md documentation](https://galaxy.ansible.com/intro#readme):

> The file is composed in [GitHub markdown](https://help.github.com/articles/markdown-basics/). Make modifications using markdown to ensure the document looks good on Galaxy and on GitHub.

I also made a galaxy account and tested the changes. Galaxy ignores the annotations, or at least doesn't perform syntax highlighting based on them. Basically, you'll end up with a nicer GitHub repo, and you might end up with a nicer readme file on galaxy in the future.

**Comment by jtyr** [comment]
Thanks for your contribution!

**Pull request merged**
